--- 
jira:
  base_url: gumgum.jira.com
  project_name: OPS
  max_issues_to_fetch: 5000
  # max_issues_to_fetch: 500

google_sheets:
  sheet_name: DevOps Team Sprint Analyzer
  tab_name: Jira Data
  # tab_name: Jira Data Test

report_columns: 
  - column_name: Issue
    type: key
    key: key
  - column_name: Summary
    type: field
    field_name: summary
  - column_name: Team
    type: custom_field
    custom_field_name: customfield_13805
  - column_name: Issue Type
    type: field
    field_name: issuetype.name
  - column_name: Type
    type: custom_field
    custom_field_name: customfield_13919
  - column_name: Story Points
    type: custom_field
    custom_field_name: customfield_10013
  - column_name: Business Value
    type: custom_field
    custom_field_name: customfield_13920
  - column_name: Status
    type: field
    field_name: status.statusCategory.name
  - column_name: Creator
    type: field
    field_name: creator.displayName
  - column_name: Assignee
    type: field
    field_name: assignee.displayName
  - column_name: Sprint
    type: custom_field
    custom_field_name: customfield_10560
    regex_capture: "name=([A-Za-z0-9 _#-]*)" 
  - column_name: Date Created
    type: field
    field_name: created
    date_formatter: google_sheets
  - column_name: Date Last Status Change
    type: field
    field_name: statuscategorychangedate
    date_formatter: google_sheets
  - column_name: Link
    type: issue_link
