name: Deploy Terraform via Terragrunt
description: Built to deploy our custom lambda-exporter module
inputs:
  env:
    description: The name of the Terragrunt environment
    required: true
  tf_action:
    description: Terraform apply or destroy?
    required: true
outputs:
  function_arn:
    description: The Lambda function's ARN
    default: 'n/a'
  source_code_hash:
    description: The Lambda-generated hash of the function's source code
    default: 'n/a'
  last_modified:
    description: The Lambda function's source code last modified date
    default: 'n/a'
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.env }}
    - ${{ inputs.tf_action }}
