# name: 'Terraform GitHub Actions'
# on:
# #   - pull_request
#   - push
# jobs:
#   terraform:
#     name: 'Terraform'
#     runs-on: ubuntu-latest
#     steps:
#       - name: 'Checkout'
#         uses: actions/checkout@master
#       - name: 'Terraform Format'
#         uses: hashicorp/terraform-github-actions@master
#         with:
#           tf_actions_version: 0.12.17
#           use_terragrunt: true
#           tf_actions_subcommand: 'fmt'
#           tf_actions_working_dir: 'terraform/terragrunt/example/'
#         #   tf_actions_comment: true
#           tf_actions_comment: false
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       - name: 'Terraform Init'
#         uses: hashicorp/terraform-github-actions@master
#         with:
#           tf_actions_version: 0.12.17
#           use_terragrunt: true
#           tg_actions_version: 0.21.6
#           tf_actions_subcommand: 'init'
#           tf_actions_working_dir: 'terraform/terragrunt/example/'
#         #   tf_actions_comment: true
#           tf_actions_comment: false
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       - name: 'Terraform Validate'
#         uses: hashicorp/terraform-github-actions@master
#         with:
#           tf_actions_version: 0.12.17
#           use_terragrunt: true
#           tg_actions_version: 0.21.6
#           tf_actions_subcommand: 'validate'
#           tf_actions_working_dir: 'terraform/terragrunt/example/'
#         #   tf_actions_comment: true
#           tf_actions_comment: false
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       - name: 'Terraform Plan'
#         uses: hashicorp/terraform-github-actions@master
#         with:
#           tf_actions_version: 0.12.17
#           use_terragrunt: true
#           tg_actions_version: 0.21.6
#           tf_actions_subcommand: 'plan'
#           tf_actions_working_dir: 'terraform/terragrunt/example/'
#         #   tf_actions_comment: true
#           tf_actions_comment: false
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

name: Deploy jira-gsheets-exporter to AWS Lambda
on: [push]
jobs:
#   hello_world_job:
#     runs-on: ubuntu-latest
#     name: A job to say hello
#     steps:
#     - name: Hello world action step
#       id: hello
#       uses: mechtron/jira-gsheets-exporter/hello-world-docker-action@github-actions
#       with:
#         who-to-greet: 'Mona the Octocat'
#     # Use the output from the `hello` step
#     - name: Get the output time
#       run: echo "The time was ${{ steps.hello.outputs.time }}"
  terragrunt_job:
    name: Terragrunt
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout this repo
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r $GITHUB_WORKSPACE/exporter/requirements.txt -t $GITHUB_WORKSPACE/exporter
    - name: Run Terragrunt step
      id: terragrunt_apply
      uses: mechtron/jira-gsheets-exporter/terragrunt-action@github-actions
      with:
        env: example
        action: apply
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        GOOGLE_SERVICE_CREDS_JSON: ${{ secrets.GOOGLE_SERVICE_CREDS_JSON }}
        JIRA_API_EMAIL: ${{ secrets.JIRA_API_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
    # Use the output from the `hello` step
    # - name: Get the output time
    #   run: echo "The time was ${{ steps.hello.outputs.time }}"
