# name: 'Terraform GitHub Actions'
# on:
# #   - pull_request
#   - push
# jobs:
#   terraform:
#     name: 'Terraform'
#     runs-on: ubuntu-latest
#     steps:
#       - name: 'Checkout'
#         uses: actions/checkout@master
#       - name: 'Terraform Format'
#         uses: hashicorp/terraform-github-actions@master
#         with:
#           tf_actions_version: 0.12.17
#           use_terragrunt: true
#           tf_actions_subcommand: 'fmt'
#           tf_actions_working_dir: 'terraform/terragrunt/example/'
#         #   tf_actions_comment: true
#           tf_actions_comment: false
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       - name: 'Terraform Init'
#         uses: hashicorp/terraform-github-actions@master
#         with:
#           tf_actions_version: 0.12.17
#           use_terragrunt: true
#           tg_actions_version: 0.21.6
#           tf_actions_subcommand: 'init'
#           tf_actions_working_dir: 'terraform/terragrunt/example/'
#         #   tf_actions_comment: true
#           tf_actions_comment: false
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       - name: 'Terraform Validate'
#         uses: hashicorp/terraform-github-actions@master
#         with:
#           tf_actions_version: 0.12.17
#           use_terragrunt: true
#           tg_actions_version: 0.21.6
#           tf_actions_subcommand: 'validate'
#           tf_actions_working_dir: 'terraform/terragrunt/example/'
#         #   tf_actions_comment: true
#           tf_actions_comment: false
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       - name: 'Terraform Plan'
#         uses: hashicorp/terraform-github-actions@master
#         with:
#           tf_actions_version: 0.12.17
#           use_terragrunt: true
#           tg_actions_version: 0.21.6
#           tf_actions_subcommand: 'plan'
#           tf_actions_working_dir: 'terraform/terragrunt/example/'
#         #   tf_actions_comment: true
#           tf_actions_comment: false
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on: [push]
jobs:
#   hello_world_job:
#     runs-on: ubuntu-latest
#     name: A job to say hello
#     steps:
#     - name: Hello world action step
#       id: hello
#       uses: mechtron/jira-gsheets-exporter/hello-world-docker-action@github-actions
#       with:
#         who-to-greet: 'Mona the Octocat'
#     # Use the output from the `hello` step
#     - name: Get the output time
#       run: echo "The time was ${{ steps.hello.outputs.time }}"
  terragrunt_job:
    runs-on: ubuntu-18.04
    name: Terragrunt
    steps:
    - name: Terragrunt apply/destroy step
      id: terragrunt_apply
      uses: mechtron/jira-gsheets-exporter/terragrunt-action@github-actions
      with:
        env: 'example'
        action: 'apply'
      volumes:
        - '/github/workspace/'
    # Use the output from the `hello` step
    # - name: Get the output time
    #   run: echo "The time was ${{ steps.hello.outputs.time }}"
