name: Deploy jira-gsheets-exporter to AWS Lambda
on: [push]
jobs:
  terragrunt_job:
    name: Build and deploy
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout this repo
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r $GITHUB_WORKSPACE/exporter/requirements.txt -t $GITHUB_WORKSPACE/exporter
    - name: Set environment
      id: set_env
      uses: mechtron/jira-gsheets-exporter/set-env-action@github-actions
    - name: Run Terragrunt
      id: run_terragrunt
      uses: mechtron/jira-gsheets-exporter/terragrunt-action@github-actions
      # if: github.ref == 'refs/heads/master'
      with:
        # env: example
        # env: ${{ 'ops' if github.ref == 'refs/heads/master' else 'example' }}
        env: ${{ steps.set_env.outputs.env }}
        action: apply
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        GOOGLE_SERVICE_CREDS_JSON: ${{ secrets.GOOGLE_SERVICE_CREDS_JSON }}
        JIRA_API_EMAIL: ${{ secrets.JIRA_API_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
    - name: Get the Terragrunt outputs
      run: |
        echo "The Lambda function's ARN is ${{ steps.run_terragrunt.outputs.function_arn }}"
        echo "The Lambda source hash is ${{ steps.run_terragrunt.outputs.source_code_hash }}"
        echo "The Lambda function's source last modified is ${{ steps.run_terragrunt.outputs.last_modified }}"
